# Generated by Django 5.1.1 on 2024-12-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manage', '0002_users_alter_stock_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Username',
        ),
    ]
