# Generated by Django 5.1.1 on 2024-12-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manage', '0003_rename_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
