# Generated by Django 5.1.1 on 2024-12-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manage', '0008_remove_history_fsr_number_remove_stock_fsr_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
