# Generated by Django 5.1.1 on 2024-12-23 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manage', '0009_alter_history_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_manage.category'),
        ),
        migrations.AlterField(
            model_name='history',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
