# Generated by Django 5.1.1 on 2024-12-23 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manage', '0010_alter_history_category_alter_history_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='history',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
