# Generated by Django 5.1.1 on 2024-12-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manage', '0013_rename_username_history_history_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='history_category',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='history_fs_number',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='history_issue_quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='history_receive_quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='history_targa_number',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='history_username',
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
