# Generated by Django 5.1.1 on 2024-12-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manage', '0014_remove_stock_history_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='price',
            new_name='purch_price',
        ),
        migrations.AddField(
            model_name='stock',
            name='sales_price',
            field=models.FloatField(default=0),
        ),
    ]
