# Generated by Django 5.1.1 on 2024-12-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manage', '0015_rename_price_stock_purch_price_stock_sales_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='history_purch_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='history_sales_price',
            field=models.FloatField(default=0),
        ),
    ]
