# Generated by Django 5.1.1 on 2024-12-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manage', '0016_history_history_purch_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='history_purch_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='history_sales_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
