# Generated by Django 5.1.1 on 2024-12-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manage', '0017_history_history_purch_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='history_onhand',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
