# Generated by Django 5.1.1 on 2024-12-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manage', '0018_history_history_onhand'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='history_stockname',
            field=models.CharField(default='Dalmart', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='notification',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='stockname',
            field=models.CharField(default='Dalmart', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='history_fs_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='history_targa_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
