# Generated by Django 5.1.1 on 2025-01-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manage', '0019_history_history_stockname_stock_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='history_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
